# Site settings
title: О Google Analytics
email: aliaksei.harabchuk@gmail.com
description: >
  Блог с рецептами для Google Analytcs, Tag Manager, Яндекс Метрикки
  с пошаговыми инструкциями и примерами
baseurl: "/metricexpert.ru" # the subpath of your site, e.g. /blog
url: "http://metricexpert.ru" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  harabchuk

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
