# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: О Google Analytics
email: aliaksei.harabchuk@gmail.com
description: >
  Блог с рецептами для Google Analytcs, Tag Manager, Яндекс Метрикки
  с пошаговыми инструкциями и примерами
baseurl: "/metricexpert.ru" # the subpath of your site, e.g. /blog
url: "http://metricexpert.ru" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  harabchuk

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
